DROP TABLE AGENCIASPUBLICITARIAS;
DROP TABLE ambito;
CREATE TABLE AMBITO (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY,
    CODIGO CHAR(2),
    AMBITO VARCHAR(20) NOT NULL,
    CONSTRAINT ID_AMBITO_PK PRIMARY KEY (ID)
);


CREATE TABLE AGENCIASPUBLICITARIAS (
    ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY, -- Id autonumérico
    NOMBRE VARCHAR(20) NOT NULL,
    ANNOCREACION DATE,
    TELEFONO VARCHAR(15),
    EMAIL VARCHAR(30),
    PROVINCIA VARCHAR(20),
    PRECIOHORA DECIMAL (7,2),
    SOPORTE VARCHAR (15),
    COBRADESPSERVICIO BOOLEAN,
    ISBN VARCHAR(12),
    AMBITO INTEGER NOT NULL,
    TrabajosRealizados INTEGER,
    CONSTRAINT ID_AGENCIAP_PK PRIMARY KEY (ID),
    CONSTRAINT AMB_AGENCIA_FK FOREIGN KEY (AMBITO) REFERENCES AMBITO (ID)
);
